extra:
  analytics:
    property: UA-105170809-5
    provider: google
site_name: Argo CD Notifications
repo_url: https://github.com/argoproj-labs/argocd-notifications
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
extra_javascript:
- assets/versions.js
extra_css:
- assets/versions.css
markdown_extensions:
- codehilite
- admonition
- pymdownx.highlight
- pymdownx.superfences
- toc:
    permalink: true
nav:
  - Overview: index.md
  - triggers.md
  - templates.md
  - subscriptions.md
  - Notification Services:
    - services/overview.md
    - services/email.md
    - services/github.md
    - services/slack.md
    - services/mattermost.md
    - services/opsgenie.md
    - services/grafana.md
    - services/teams.md
    - services/telegram.md
    - services/webhook.md
    - services/rocketchat.md
  - catalog.md
  - troubleshooting.md
  - Bots:
    - bots/overview.md
    - bots/slack-bot.md
    - bots/opsgenie-bot.md
    - bots/telegram-bot.md
  - monitoring.md
  - Upgrading:
    - upgrading/0.x-1.0.md
